// Generated by gencpp from file solar_buggy/Controller.msg
// DO NOT EDIT!


#ifndef SOLAR_BUGGY_MESSAGE_CONTROLLER_H
#define SOLAR_BUGGY_MESSAGE_CONTROLLER_H

#include <ros/service_traits.h>


#include <solar_buggy/ControllerRequest.h>
#include <solar_buggy/ControllerResponse.h>


namespace solar_buggy
{

struct Controller
{

typedef ControllerRequest Request;
typedef ControllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Controller
} // namespace solar_buggy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::solar_buggy::Controller > {
  static const char* value()
  {
    return "770770ca4208a49b403ae37e8aa24498";
  }

  static const char* value(const ::solar_buggy::Controller&) { return value(); }
};

template<>
struct DataType< ::solar_buggy::Controller > {
  static const char* value()
  {
    return "solar_buggy/Controller";
  }

  static const char* value(const ::solar_buggy::Controller&) { return value(); }
};


// service_traits::MD5Sum< ::solar_buggy::ControllerRequest> should match 
// service_traits::MD5Sum< ::solar_buggy::Controller > 
template<>
struct MD5Sum< ::solar_buggy::ControllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::solar_buggy::Controller >::value();
  }
  static const char* value(const ::solar_buggy::ControllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::solar_buggy::ControllerRequest> should match 
// service_traits::DataType< ::solar_buggy::Controller > 
template<>
struct DataType< ::solar_buggy::ControllerRequest>
{
  static const char* value()
  {
    return DataType< ::solar_buggy::Controller >::value();
  }
  static const char* value(const ::solar_buggy::ControllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::solar_buggy::ControllerResponse> should match 
// service_traits::MD5Sum< ::solar_buggy::Controller > 
template<>
struct MD5Sum< ::solar_buggy::ControllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::solar_buggy::Controller >::value();
  }
  static const char* value(const ::solar_buggy::ControllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::solar_buggy::ControllerResponse> should match 
// service_traits::DataType< ::solar_buggy::Controller > 
template<>
struct DataType< ::solar_buggy::ControllerResponse>
{
  static const char* value()
  {
    return DataType< ::solar_buggy::Controller >::value();
  }
  static const char* value(const ::solar_buggy::ControllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SOLAR_BUGGY_MESSAGE_CONTROLLER_H
