// Generated by gencpp from file solar_buggy/ControllerResponse.msg
// DO NOT EDIT!


#ifndef SOLAR_BUGGY_MESSAGE_CONTROLLERRESPONSE_H
#define SOLAR_BUGGY_MESSAGE_CONTROLLERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace solar_buggy
{
template <class ContainerAllocator>
struct ControllerResponse_
{
  typedef ControllerResponse_<ContainerAllocator> Type;

  ControllerResponse_()
    : return_value(0)  {
    }
  ControllerResponse_(const ContainerAllocator& _alloc)
    : return_value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _return_value_type;
  _return_value_type return_value;





  typedef boost::shared_ptr< ::solar_buggy::ControllerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::solar_buggy::ControllerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerResponse_

typedef ::solar_buggy::ControllerResponse_<std::allocator<void> > ControllerResponse;

typedef boost::shared_ptr< ::solar_buggy::ControllerResponse > ControllerResponsePtr;
typedef boost::shared_ptr< ::solar_buggy::ControllerResponse const> ControllerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::solar_buggy::ControllerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::solar_buggy::ControllerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace solar_buggy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::solar_buggy::ControllerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::solar_buggy::ControllerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::solar_buggy::ControllerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::solar_buggy::ControllerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::solar_buggy::ControllerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::solar_buggy::ControllerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::solar_buggy::ControllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "770770ca4208a49b403ae37e8aa24498";
  }

  static const char* value(const ::solar_buggy::ControllerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x770770ca4208a49bULL;
  static const uint64_t static_value2 = 0x403ae37e8aa24498ULL;
};

template<class ContainerAllocator>
struct DataType< ::solar_buggy::ControllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "solar_buggy/ControllerResponse";
  }

  static const char* value(const ::solar_buggy::ControllerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::solar_buggy::ControllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 return_value\n\
\n\
";
  }

  static const char* value(const ::solar_buggy::ControllerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::solar_buggy::ControllerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::solar_buggy::ControllerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::solar_buggy::ControllerResponse_<ContainerAllocator>& v)
  {
    s << indent << "return_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.return_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOLAR_BUGGY_MESSAGE_CONTROLLERRESPONSE_H
