// Generated by gencpp from file solar_buggy/ControllerRequest.msg
// DO NOT EDIT!


#ifndef SOLAR_BUGGY_MESSAGE_CONTROLLERREQUEST_H
#define SOLAR_BUGGY_MESSAGE_CONTROLLERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace solar_buggy
{
template <class ContainerAllocator>
struct ControllerRequest_
{
  typedef ControllerRequest_<ContainerAllocator> Type;

  ControllerRequest_()
    {
    }
  ControllerRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::solar_buggy::ControllerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::solar_buggy::ControllerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerRequest_

typedef ::solar_buggy::ControllerRequest_<std::allocator<void> > ControllerRequest;

typedef boost::shared_ptr< ::solar_buggy::ControllerRequest > ControllerRequestPtr;
typedef boost::shared_ptr< ::solar_buggy::ControllerRequest const> ControllerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::solar_buggy::ControllerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::solar_buggy::ControllerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace solar_buggy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::solar_buggy::ControllerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::solar_buggy::ControllerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::solar_buggy::ControllerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::solar_buggy::ControllerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::solar_buggy::ControllerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::solar_buggy::ControllerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::solar_buggy::ControllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::solar_buggy::ControllerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::solar_buggy::ControllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "solar_buggy/ControllerRequest";
  }

  static const char* value(const ::solar_buggy::ControllerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::solar_buggy::ControllerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::solar_buggy::ControllerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::solar_buggy::ControllerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::solar_buggy::ControllerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::solar_buggy::ControllerRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SOLAR_BUGGY_MESSAGE_CONTROLLERREQUEST_H
